spring:
  application:
    name: language_practice

  datasource:
    url: jdbc:postgresql://localhost:5432/language_practice
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
    show-sql: true

server:
  port: 8000
