spring:
  application:
    name: language_practice

  datasource:
    url: jdbc:postgresql://localhost:5432/language_practice
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: hoangvudx2004@gmail.com
    password: ezrhnhtdsnejmawi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          starttls.required: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
    show-sql: true

server:
  port: 8000

jwt:
  signerKey: "3m47O+gM3Sc0lc9I5pMhfGFZMoqvbFtLoNs6Lmq9nOg="
  valid-duration: 3600000
  refreshable-duration: 36000
